services:
  # BASE DE DATOS
  base_datos_psql:
    image: postgres:15-alpine
    container_name: bebras_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FRONTEND (Next.js)
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodo_app_servidor
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=base_datos_psql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - base_datos_psql

volumes:
  postgres_data:
    driver: local